### ISSUE TITLE
Cool find

### ISSUE THREAD

**Issue by glouw** [milgra/headerlessc#1]
But I think its a GNU extension. It'd be amazing if it were ISO standard.

**Comment by glouw** [comment]
This peaked my interest so I decided to give it a go:
https://github.com/glouw/cheaderless

Its all ISO-C89 so it'll compile just about anywhere. If theres a way to expand the

```
void fun()
#ifdef OBJECT_NAME
    ;
#else
{
}
```
declaration into a convenient macro then we're in business.

**Comment by glouw** [comment]
Additionally, if we could get the preprocessor to turn 

```
import(WATCH)
```

into

```
#define WATCH
#include "WATCH.c"
```

We'd have a beautiful solution.

As an aside, the build system will still resolve dependencies as object files are still compiled. Including a .c file just swaps the definition for the declaration.

**Comment by milgra** [comment]
wow, that's interesting, I'll give it a try, thank you!

**Comment by glouw** [comment]
I'm actually now really fascinated by this.

I took it one step further. In C99 there is the __VA_ARGS__ definition. It lets you do:

```
#undef defines
#ifdef PERSON
    #define defines(...);
#else
    #define defines(...){__VA_ARGS__}
#endif
```

which essentially lets you wrap your functions in round brackets:

```
Person pnew(void) defines
(
    Person p;
    p.age = 22;
    p.height = 200;
    p.weight = 220;
    p.watch = wnew();
    return p;
)
```

Including the modules with a 

```
#define PERSON
#include "PERSON.c"
```

will turn the function definitions into declarations.

Alas, I have not figured out an nice way to have global variables work, but a decent architecture will not ever need globals anyway.

**Comment by glouw** [comment]
Updated. Have a look again at:
https://github.com/glouw/cheaderless

Once again, if there were a way to run the preprocessor twice we could turn

```
#define PERSON
#include "PERSON.c"
```

into

```
#import PERSON
```

But in my opinion its not necessary and is a small price to pay for finally getting rid of headers.

**Comment by milgra** [comment]
Wow, you've just recreated my [class-c](https://github.com/milgra/clc) programming language with five macro lines, that's pure genius! But those and the round brackets makes things a little more complicated and fragile.

**Comment by glouw** [comment]
https://gustedt.wordpress.com/2018/11/12/c2x/

The C2X revision may have your include header level macro apart of the standard with __has_include:

http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2101.htm

Its just a matter of waiting 5-10 years.

**Comment by milgra** [comment]
Maaan, I have problems with language committees because they have a need to add stuff and never remove something. For me const and static words were already too much in the original C specification :) Let's hope they really simplify it.

**Comment by glouw** [comment]
I have an unhealthy obsession with const - to each their own - but we're also (maybe) getting static_assert, so that's exciting

**Comment by glouw** [comment]
I gave clc a read. Its pretty well built. I'm gonna give it a go at home someday.

**Comment by milgra** [comment]
Thanks, but I left it, I don't believe in OOP any more. Headerless-C is my way! :)

**Comment by glouw** [comment]
I have a very strong urge to agree with you - we need headerless C - though we don't quite have reasonable tools.

I'm gonna try building a C front end that combines functions and structs. I'll keep you posted.

**Comment by ghost** [comment]
I came up with [this](https://github.com/recidivism5/headerless_c) before finding this conversation. What do you guys think?

**Comment by glouw** [comment]
LGTM @recidivism5

**Comment by milgra** [comment]
Nice way to trick Visual Studio :)  I use emacs so Intellisense is not an issue for me.
